config/routes.rb
Rails.application.routes.draw do
  resources :messages
  devise_for :users
  root 'pages#index'
  get 'messages' => 'messages#index'
  post 'messages' => 'messages#create'

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  before_save :created_at
  def timestamp
    created_at_field = Time.in_time_zone.strftime("%a, %B %d, %I:%M %p")
  end
  def change
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_message, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
		@messages = Message.all
    @message = Message.new
	end
  def new
    @message = current_user.messages.build
  end
  def show
  end
  def create
    @message = current_user.messages.build(message_params)
    if @message.save
      redirect_to '/messages'
    else
      render 'new'
  end
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to '/messages', notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @messages }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully deleted.' }
      format.json { head :no_content }
    end
  end
end
  private
  def set_message
    @message = Message.find(params[:id])
  end

  def correct_user
    @message = current_user.messages.find_by(id: params[:id])
    redirect_to messages_path, notice: "Unable to locate page." if @message.nil?
  end
  def message_params
    params.require(:message).permit(:content, :username)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @message = Message.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Houge</title>
  <meta http-equiv="refresh" content="150">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
</head>
<body>

  <%= yield %>

<script src="assets/js/jquery-2.1.4.min.js"></script>
<script src="assets/js/functions.js" type="text/javascript"></script>
</body>
</html>

app/views/messages/edit.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag(:div, msg, class: "alert alert-#{name}")%>
<% end %>
<%= form_for(@message) do |f| %>
<div class="overlay">
  <div class="modal">
    <div class="text">
      <h1 class="lead">Edit Message</h1>
    </div>
    <% if user_signed_in? %>
    <div class="i-text">
      <div class="t-field" required="required"><p><%= f.text_area :content, required: true, :class => 'p t-field', :placeholder => "What's bothering you?", :rows => '2', :cols => '36' %></p></div>
      <div type="submit"><h1><%= f.submit "Submit", :class => 'b-submit' %></h1></div>
      <%= link_to 'Back', messages_path %>
    </div>
    <% end %>
  </div>
</div>
<% end %>

app/views/messages/index.html.erb
<div class="container">
  <div class="msg-head">
    <h1>Houge Thoughts</h1>
    <% if user_signed_in? %>
      <p class="leave"><%= link_to "Log Out", destroy_user_session_path, method: :delete %></p>
      <p class="m-edituser"><%= link_to "Edit User", edit_user_registration_path %></p>
    <% end %>
  </div>
  <div class="message-container">
    <% @messages.reverse_each do |message| %>
    <div class="message animated fadeIn">
      <p class="content"><%= message.content %></p>
      <div class="m-info">
        <p class="user-name">by <%= message.user.username if message.user %> |</p>
        <p class="time"><%= message.created_at.strftime("%a, %B %d, %I:%M %p") %></p>
        <% if message.user == current_user %>
            <p class="m-edit"><%= link_to '', edit_message_path(message) %></p>
            <p class="m-delete"><%= link_to '✖', message, method: :delete, data: { confirm: 'Are you sure?' } %></p>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>
  <%= form_for(@message) do |f| %>
    <div class="input-text">
      <div class="text-field" required="required"><p><%= f.text_area :content, required: true, :class => 'p text-field', :placeholder => "What's bothering you?", :rows => '2', :cols => '36' %></p></div>
      <div class="btn-submit" type="submit"><h1><%= f.submit "Submit", :class => 'btn-submit' %></h1></div>
    </div>
  </div>
  <% end %>
</div>

app/views/messages/show.html.erb
<%= link_to 'Back', message_path %>

app/views/pages/index.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag(:div, msg, class: "alert alert-#{name}")%>
<% end %>
<%= form_for(@message) do |f| %>
<div class="overlay">
  <div class="modal">
    <div class="text">
      <h1 class="lead">What's wrong</br>today, Houge?</h1>
      <p>If you were Houge, what would be bothering you today?</p>
    </div>
    <% if user_signed_in? %>
    <div class="i-text">
      <div class="t-field" required="required"><p><%= f.text_area :content, required: true, :class => 'p t-field', :placeholder => "What's bothering you?", :rows => '2', :cols => '36' %></p></div>
      <div type="submit"><h1><%= f.submit "Submit", :class => 'b-submit' %></h1></div>
      <%= link_to 'All Messages', messages_path %></br>
      <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
    </div>
    <% else %>
    <p class="logup">
      <%= link_to "Log In", new_user_session_path, :class => 'home-b-submit' %>
      <%= link_to "Sign Up", new_user_registration_path, :class => 'home-b-submit' %>
    <p>
    <% end %>

  </div>
</div>
<% end %>